### ISSUE TITLE
Not able to import the new version 

### ISSUE THREAD

**Issue by ghost** [sockeqwe/sqlbrite-dao#19] opened 2015-10-15 09:08 UTC
This is really weird, I am trying to import the latest release but for some reason everything breaks, only the annotation  module is imported the Dao and object mapper are not imported

Note: I am using them in a library module which I use internally

**Comment by sockeqwe** [comment] 2015-10-15 09:23
Any error message? Try to build your project via command line: `gradlew clean build --stacktrace`

**Comment by sockeqwe** [comment] 2015-10-15 09:25
Btw. there were API breaking changes from `0.2.x` to `0.4.0`, but that is not your problem, isn't it? You are talking about including the dependency to the library, right?

**Comment by ghost** [comment] 2015-10-15 09:28
Yes the library here is my own though and SQLBrite Dao is a dependency in it

**Comment by ghost** [comment] 2015-10-15 09:31
The error basically is that the Dao class was not found and hence all methods in the class weren't either

**Comment by sockeqwe** [comment] 2015-10-15 09:35
Sounds weird, for me it's working as usual and I can't see any reason why it should make a difference if your projects is an android app or an android library ... Stupid question: but have you already tried to make a clean and rebuild in android studio.

**Comment by ghost** [comment] 2015-10-15 09:37
Exactly I am not able to understand the problem either, I have tried
rebuild, clean and also Invalides caches and restarted android studio,
really weird

**Comment by sockeqwe** [comment] 2015-11-03 10:18
I close this issue. If the problem is still not solved, feel free to reopen this issue

**Closed as completed by sockeqwe** 2015-11-03 10:18 UTC

**Comment by ghost** [comment] 2015-11-03 10:26
Cool i solved it, if anyone stumbles here this is how I solved it, I don't know if this problem is because of android studio or something else 

I had to import the new version as a library project, remove the gradle dependency and then fix all the errors. 

After this i was able to remove the library project and go back to the gradle dependecy

PS I still can't figure out what was causing the problem

**Comment by harinair** [comment] 2015-11-09 01:11
I have encountered this weird error when upgrading from 0.2.2. Read more about it in #24.
